// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using MVC_leaflet.DB;

#nullable disable

namespace MVC_leaflet.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_leaflet.DB.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressObjectCode")
                        .HasColumnType("int");

                    b.Property<string>("AddressObjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AddressObjectTypeCode")
                        .HasColumnType("int");

                    b.Property<decimal>("CentroidDDECoordinate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CentroidDDNCoordinate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CentroidXCoordinate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CentroidYCoordinate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeCD")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
